In [ ]:
#importing
import numpy as np

arrays

In [ ]:
a=np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [ ]:
b=np.array([[2,3,4,5],[6,7,8,9]])
print(b)

[[2 3 4 5]
 [6 7 8 9]]


In [ ]:
c=np.array([[[2,3,4],[5,6,7]],[[8,1,5],[1,3,5]]])
print(c)

[[[2 3 4]
  [5 6 7]]

 [[8 1 5]
  [1 3 5]]]


In [ ]:
#checking dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [ ]:
d=np.ones((2,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
e=np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
f=np.eye(4,3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
g=np.arange(3,31,3)
print(g)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
g=np.arange(3,31,3).reshape(2,5)
print(g)

[[ 3  6  9 12 15]
 [18 21 24 27 30]]


In [ ]:
h=np.arange(5,1001,5)
print(h)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

In [ ]:
i=np.linspace(2,12,10)
print(i)

[ 2.          3.11111111  4.22222222  5.33333333  6.44444444  7.55555556
  8.66666667  9.77777778 10.88888889 12.        ]


In [ ]:
j=np.arange(1,7).reshape(2,3)
print(j)
k=np.arange(5,11).reshape(2,3)
print(k)

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]]


In [ ]:
print(j+k)

[[ 6  8 10]
 [12 14 16]]


In [ ]:
m=np.sum((j,k),axis=0)
print(m)

[[ 6  8 10]
 [12 14 16]]


In [ ]:
n=np.sum((j,k),axis=1)
print(n)

[[ 5  7  9]
 [13 15 17]]


In [ ]:
o=np.sum((j,k),axis=2)
print(o)

[[ 6 15]
 [18 27]]


In [ ]:
b=np.array([25,289,361,81])
for i in b:
  print(np.sqrt(i),"square root of",i)

5.0 square root of 25
17.0 square root of 289
19.0 square root of 361
9.0 square root of 81


In [ ]:
a=np.array([34,35,])